/**
 * This file will be generated by Electrode Native with imports of all
 * MiniApps / JS API Implementations part of the Composite.
 *
 * For example:
 *
 * import 'feature-one-miniapp';
 * import 'feature-two-miniapp';
 *
 * This file should be imported in index.js
 */
